; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

; change to T5-ePaper if you have ESP32-WROVER based device (or use 'pio run -e T5-ePaper')
default_envs = T5-ePaper-S3

; src_dir = examples/button
; src_dir = examples/demo
; src_dir = examples/drawExample
; src_dir = examples/drawImages
; src_dir = examples/grayscale_test
; src_dir = examples/screen_repair
; src_dir = examples/spi_driver
; src_dir = examples/touch
; src_dir = examples/wifi_sync
; src_dir = examples/sleep
src_dir = examples/ha_calendar

[env]
lib_extra_dirs = ${PROJECT_DIR}
platform = espressif32@6.12.0
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0

monitor_filters = 
	default
	esp32_exception_decoder

lib_deps = 
	lewisxhe/SensorLib @ 0.3.1
	lennarthennigs/Button2 @ 2.3.2
	Wire
	SPI
    bblanchon/ArduinoJson@^7.4.2

[env:T5-ePaper-S3]
extends = env
board = T5-ePaper-S3
build_flags = ${env.build_flags}
	-DLILYGO_T5_EPD47_S3

; older ESP32-WROVER-E device. Note: not all examples fully work.
; https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/issues/177#issuecomment-3747498636
[env:T5-ePaper]
extends = env
board = T5-ePaper
upload_port = /dev/ttyUSB0
build_flags = ${env.build_flags}
	-DLILYGO_T5_EPD47
  -DESP_EXT1_WAKEUP_ANY_LOW=ESP_EXT1_WAKEUP_ALL_LOW
